name       : editorconfig-core-c
version    : 0.12.2
release    : 1
source     :
    - https://github.com/editorconfig/editorconfig-core-c/archive/v0.12.2.tar.gz : 8a63ae63d3a2f2a202acbd94a6cbe3fa4450c2658e33e922683af33c48a9115d
license    : BSD-2-Clause
component  : programming.library
summary    : EditorConfig core library written in C
description: |
    EditorConfig makes it easy to maintain the correct coding style when switching between different text editors and between different projects. The EditorConfig project maintains a file format and plugins for various text editors which allow this file format to be read and used by those editors.
builddeps  :
    - doxygen
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.a
