name       : editorconfig-core-c
version    : 0.12.3
release    : 2
source     :
    - https://github.com/editorconfig/editorconfig-core-c/archive/v0.12.3.tar.gz : 64edf79500e104e47035cace903f5c299edba778dcff71b814b7095a9f14cbc1
license    : BSD-2-Clause
component  : programming.library
summary    : EditorConfig core library written in C
description: |
    EditorConfig makes it easy to maintain the correct coding style when switching between different text editors and between different projects. The EditorConfig project maintains a file format and plugins for various text editors which allow this file format to be read and used by those editors.
builddeps  :
    - pkgconfig(libpcre2-posix)
    - doxygen
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/%libdir%/*.a
